//==================================================
// This file contains the Excluded objects
// Generated By User: shirley
// Format Version: 2
// Date: Mon Dec 23 10:58:41 2024
// ExclMode: default
//==================================================
CHECKSUM: "3827836723"
INSTANCE:uvm_custom_install_recording
CHECKSUM: "4007355041"
INSTANCE:top.in
CHECKSUM: "4124711733"
INSTANCE:uvm_custom_install_verdi_recording
CHECKSUM: "595382730 451979317"
INSTANCE: top.DUT.control
Toggle PRDATA [31] "logic PRDATA[31:0]"
Toggle PRDATA [8] "logic PRDATA[31:0]"
Toggle PRDATA [9] "logic PRDATA[31:0]"
Toggle PRDATA [10] "logic PRDATA[31:0]"
Toggle PRDATA [11] "logic PRDATA[31:0]"
Toggle PRDATA [12] "logic PRDATA[31:0]"
Toggle PRDATA [13] "logic PRDATA[31:0]"
Toggle PRDATA [14] "logic PRDATA[31:0]"
Toggle PRDATA [15] "logic PRDATA[31:0]"
Toggle PRDATA [16] "logic PRDATA[31:0]"
Toggle PRDATA [17] "logic PRDATA[31:0]"
Toggle PRDATA [18] "logic PRDATA[31:0]"
Toggle PRDATA [19] "logic PRDATA[31:0]"
Toggle PRDATA [20] "logic PRDATA[31:0]"
Toggle PRDATA [21] "logic PRDATA[31:0]"
Toggle PRDATA [22] "logic PRDATA[31:0]"
Toggle PRDATA [23] "logic PRDATA[31:0]"
Toggle PRDATA [24] "logic PRDATA[31:0]"
Toggle PRDATA [25] "logic PRDATA[31:0]"
Toggle PRDATA [26] "logic PRDATA[31:0]"
Toggle PRDATA [27] "logic PRDATA[31:0]"
Toggle PRDATA [28] "logic PRDATA[31:0]"
Toggle PRDATA [29] "logic PRDATA[31:0]"
Toggle PRDATA [30] "logic PRDATA[31:0]"
Toggle dcd_int "logic dcd_int"
Toggle dcd_1 "logic dcd_1"
Toggle dcd_0 "logic dcd_0"
Toggle cts_0 "logic cts_0"
Toggle cts_1 "logic cts_1"
